name: Deploy to Netlify [PROD]

on:
  push:
    branches:
      - main

permissions:
  actions: read # Needed for nx-set-shas when run on the main branch
  contents: read # Needed for nx-set-shas when run on the main branch
  pull-requests: write # Needed to create a comment on the PR

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        cache: "npm"
        cache-dependency-path: "package-lock.json"

    - name: Install dependencies
      run: npm ci

    - name: Read from first JSON file and export value
      id: extract_json_1
      run: |
        MARKETPLACE=$(jq -r '.text' marketplace.json)
        echo "MARKETPLACE=${MARKETPLACE}" >> $GITHUB_ENV

    - name: Read from second JSON file and export value
      id: extract_json_2
      run: |
        VALUE2=$(jq -r '.text' showcase.json)
        echo "SHOWCASE=${VALUE2}" >> $GITHUB_ENV

    - name: Use the exported values
      run: |
        echo "The first value is: ${{ env.MARKETPLACE }}"
        echo "The second value is: ${{ env.SHOWCASE }}"
