name: Deploy to hosting server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to OVH hosting
        uses: pitscher/ovh-deploy-hosting-action@v1
        env:
          OVH_HOSTING_USER: ${{ secrets.OVH_HOSTING_USER }}
          OVH_HOSTING_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }}
          OVH_HOSTING_DOMAIN: ${{ secrets.OVH_HOSTING_DOMAIN }}
          REPOSITORY_NAME: test-ci
          REPOSITORY_URL: https://github.com/louiiuol/test-ci.git
